### ISSUE TITLE
Fix Bottom Nav Bug

### ISSUE THREAD

**Issue by AhmadTakkoush** [AhmadTakkoush/Source#1]
Whenever I try to switch tabs from the bottom navigation, the app restarts.

**Comment by nurettinabaci** [comment]
There isn't any bottom navigation? What is the problem exactly? Is the problem about activity lifecycle?

**Comment by AhmadTakkoush** [comment]
Sorry I thought I had my code pushed, you can check it out now. I want to go to each fragment when I click on the home or explore for example it explore fragment or stays home

**Comment by nurettinabaci** [comment]
PR #3 
Can you run it? I think it will work, otherwise fragments may have problem.
