### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by AhmadTakkoush** [AhmadTakkoush/Source#2]
Help with Logout Button functionality

**Comment by CBruno98** [comment]
I can work on this

**Comment by AhmadTakkoush** [comment]
@CBruno98 Sure go ahead :)

**Comment by hardikkhanna** [comment]
> Help with Logout Button functionality

I want to work on this

**Comment by AhmadTakkoush** [comment]
@hardikkhanna be my guest
